### A development ground for the dataloader and associated data util classes

In [1]:
# from utils.data_utils import CMIP, SODA
import xarray as xr
import numpy as np
import subprocess
import torch
import sys
DATA_ROOT = subprocess.check_output(['git', 'rev-parse', '--show-toplevel']).strip().decode('utf-8') + '/data'
sys.path.append('/scratch/users/ethanz/enso/data_retrieval')
sys.path.append('/scratch/users/ethanz/enso')
from global_vars import *
from cmip_data_utils import get_best_cmip_models
from utils.data_utils import CMIP, SODA
# test = SODA()

In [3]:
test = get_best_cmip_models(5)
test = test['model_name'].to_numpy()

big_data = xr.load_dataset('../merged_data/CMIP_merged.nc')
members = [str(sim_id) for sim_id in big_data['simulation_id'].to_numpy() if sim_id.split(':')[0] in test]
print(np.shape(big_data.sel(simulation_id=members)['oni'].to_numpy()))
print(np.sum(np.isnan(big_data.sel(simulation_id=members)['oni'].to_numpy())))

(16, 1980)
32


In [4]:
godas = xr.load_dataset('../merged_data/GODAS.nc')
print(len(godas.time.values))
print(np.shape(godas['oni'].to_numpy()))
godas['lat']

538
(538,)


<xarray.DataArray 'lat' (lat: 24)> Size: 192B
array([-57.5, -52.5, -47.5, -42.5, -37.5, -32.5, -27.5, -22.5, -17.5, -12.5,
        -7.5,  -2.5,   2.5,   7.5,  12.5,  17.5,  22.5,  27.5,  32.5,  37.5,
        42.5,  47.5,  52.5,  57.5])
Coordinates:
    lev      float32 4B 5.0
  * lat      (lat) float64 192B -57.5 -52.5 -47.5 -42.5 ... 42.5 47.5 52.5 57.5
Attributes:
    standard_name:  latitude

In [5]:
soda = xr.load_dataset('../merged_data/SODA.nc')
print(np.shape(soda['oni'].to_numpy()))
soda['lat']

(1236,)


<xarray.DataArray 'lat' (lat: 24)> Size: 192B
array([-57.5, -52.5, -47.5, -42.5, -37.5, -32.5, -27.5, -22.5, -17.5, -12.5,
        -7.5,  -2.5,   2.5,   7.5,  12.5,  17.5,  22.5,  27.5,  32.5,  37.5,
        42.5,  47.5,  52.5,  57.5])
Coordinates:
    lev      float64 8B 5.01
  * lat      (lat) float64 192B -57.5 -52.5 -47.5 -42.5 ... 42.5 47.5 52.5 57.5
Attributes:
    standard_name:  latitude

In [62]:
a = big_data.sel(simulation_id=members[0])
b = a.isel(time=0)
b['lon'].to_numpy()

array([-177.5, -172.5, -167.5, -162.5, -157.5, -152.5, -147.5, -142.5,
       -137.5, -132.5, -127.5, -122.5, -117.5, -112.5, -107.5, -102.5,
        -97.5,  -92.5,  -87.5,  -82.5,  -77.5,  -72.5,  -67.5,  -62.5,
        -57.5,  -52.5,  -47.5,  -42.5,  -37.5,  -32.5,  -27.5,  -22.5,
        -17.5,  -12.5,   -7.5,   -2.5,    2.5,    7.5,   12.5,   17.5,
         22.5,   27.5,   32.5,   37.5,   42.5,   47.5,   52.5,   57.5,
         62.5,   67.5,   72.5,   77.5,   82.5,   87.5,   92.5,   97.5,
        102.5,  107.5,  112.5,  117.5,  122.5,  127.5,  132.5,  137.5,
        142.5,  147.5,  152.5,  157.5,  162.5,  167.5,  172.5,  177.5])

In [28]:
test = CMIP_big()
print(test.window_indices)
print(np.shape(test.window_indices))
print(test.get_labels())
print(np.shape(test.get_labels()))
print(test.members)

[[    0     1     2 ...    33    34    35]
 [    1     2     3 ...    34    35    36]
 [    2     3     4 ...    35    36    37]
 ...
 [31242 31243 31244 ... 31275 31276 31277]
 [31243 31244 31245 ... 31276 31277 31278]
 [31244 31245 31246 ... 31277 31278 31279]]
(30720, 36)
[[-0.4682379  -0.65431    -0.73430765 ... -0.4587148  -0.44795918
  -0.4677848 ]
 [-0.65431    -0.73430765 -0.7203206  ... -0.44795918 -0.4677848
  -0.49650413]
 [-0.73430765 -0.7203206  -0.31820384 ... -0.4677848  -0.49650413
  -0.5431284 ]
 ...
 [ 1.3710555   1.3713835   1.3863987  ... -0.33040228 -0.6818594
  -0.69851017]
 [ 1.3713835   1.3863987   1.4984897  ... -0.6818594  -0.69851017
  -0.71116376]
 [ 1.3863987   1.4984897   1.8329997  ... -0.69851017 -0.71116376
  -0.6602729 ]]
(30720, 24)
['EC-Earth3-Veg-LR:r1i1p1f1', 'EC-Earth3-Veg-LR:r2i1p1f1', 'EC-Earth3-Veg-LR:r3i1p1f1', 'EC-Earth3-Veg:r14i1p1f1', 'EC-Earth3-Veg:r2i1p1f1', 'EC-Earth3-Veg:r3i1p1f1', 'EC-Earth3-Veg:r4i1p1f1', 'EC-Earth3-Veg:r5i1p1f1', 'EC

In [3]:
soda = SODA()
soda_data = xr.load_dataset('../merged_data/SODA.nc')


In [9]:
print(soda_data['oni'].to_numpy()[36])
print(soda_data['oni'].to_numpy()[-2])
print(soda.get_labels())
print(soda.window_indices)

-0.24164295
-1.4853014
[[-0.24164295 -0.584523   -0.94119865 ... -0.583987   -0.46458212
  -0.27401453]
 [-0.584523   -0.94119865 -1.0769753  ... -0.46458212 -0.27401453
  -0.17616327]
 [-0.94119865 -1.0769753  -0.9277924  ... -0.27401453 -0.17616327
  -0.25127807]
 ...
 [-0.8294339  -0.9407738  -0.88988    ... -0.6849893  -0.69580203
  -0.80722696]
 [-0.9407738  -0.88988    -0.7394064  ... -0.69580203 -0.80722696
  -1.1424342 ]
 [-0.88988    -0.7394064  -0.49150738 ... -0.80722696 -1.1424342
  -1.4853014 ]]
[[   0    1    2 ...   33   34   35]
 [   1    2    3 ...   34   35   36]
 [   2    3    4 ...   35   36   37]
 ...
 [1173 1174 1175 ... 1206 1207 1208]
 [1174 1175 1176 ... 1207 1208 1209]
 [1175 1176 1177 ... 1208 1209 1210]]


In [30]:
print(big_data.sel(simulation_id='EC-Earth3-Veg-LR:r1i1p1f1').isel(time=36)['oni'].to_numpy())
print(big_data.sel(simulation_id='HadGEM3-GC31-MM:r4i1p1f3').isel(time=-2)['oni'].to_numpy())

-0.4682379
-0.6602729


In [6]:
checkpoint_path = 'checkpoints/GATLSTM_train_small_updatedloaders_1e-4_20241207_213003/epoch=0-train_loss=0.58.ckpt'
checkpoint = torch.load(checkpoint_path)

# Access the logger states
if "logger_states" in checkpoint:
    logger_states = checkpoint["logger_states"]

    # Wandb logger states should be stored with the key 'wandb'
    wandb_state = logger_states.get("wandb", {})
    run_id = wandb_state.get("id")  # Extract the Wandb run ID

    if run_id:
        print(f"Wandb Run ID: {run_id}")
    else:
        print("Wandb Run ID not found in checkpoint.")
else:
    print("No logger states found in checkpoint.")

No logger states found in checkpoint.


/tmp/ipykernel_212114/2714231489.py:2: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(checkpoint_path)


In [3]:
print(np.shape(test.get_labels()))
print(np.shape(test.window_indices))

(1165, 24)
(1165, 36)


In [ ]:
print(np.shape(fuck.window_indices))

In [3]:
cmip = xr.load_dataset(f'{DATA_ROOT}/SODA/raw/SODA_train.nc')
labels = xr.load_dataset(f'{DATA_ROOT}/SODA/raw/SODA_label.nc')

In [4]:
print(labels['nino'][0].to_numpy())
print(test.get_labels()[0]) # checks out

print(cmip.isel(year=0, month=0)['sst'].to_numpy())
print(torch.load(f'{DATA_ROOT}/SODA/processed/grid_0.pt')['x']) # checks out

[-0.40720701 -0.20244436 -0.10386104 -0.02910841 -0.13252996 -0.25527564
 -0.3326247  -0.26293179 -0.08058987  0.10612228  0.21165498  0.16504486
  0.06697161  0.00999126 -0.00164753 -0.06598581 -0.14728385 -0.1915542
 -0.17029583 -0.19376083 -0.27808595 -0.39393583 -0.49975768 -0.58400702
 -0.73201811 -0.72508991 -0.58416802 -0.31754819 -0.12046373 -0.03802495
  0.013173    0.06823147  0.0597352   0.02755602  0.011619   -0.04931002]
[-0.04931002 -0.2593078  -0.56157684 -0.72061253 -0.67269957 -0.58430457
 -0.5273878  -0.4824861  -0.37052664 -0.28829426 -0.31192511 -0.36046785
 -0.32623523 -0.12333407  0.02138779  0.02895211 -0.16465297 -0.38959804
 -0.51858526 -0.54723388 -0.60607356 -0.58923191 -0.3572121  -0.04338433]
[[ 1.8618509   2.6930773   2.0068998  ...  1.749043    1.6889814
   1.6952012 ]
 [ 1.1124177   1.6091517   1.6938334  ...  1.3404628   1.4752474
   1.5027997 ]
 [ 1.2253761   1.2931638   1.520402   ...  0.42051327  1.1427035
   1.2884156 ]
 ...
 [-1.3888688  -0.3802516

/tmp/ipykernel_255371/1780531406.py:5: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  print(torch.load(f'{DATA_ROOT}/SODA/processed/grid_0.pt')['x']) # checks out


In [9]:
cmip = CMIP()

In [3]:
print(np.shape(cmip.window_indices))
print(np.shape(cmip.get_labels()))
print(len(cmip))

(54620, 36)
(54620, 24)
55740


In [45]:
cmip_data = xr.load_dataset(f'{DATA_ROOT}/CMIP/raw/CMIP_train.nc')
cmip_labels = xr.load_dataset(f'{DATA_ROOT}/CMIP/raw/CMIP_label.nc')
cmip_data

<xarray.Dataset> Size: 9GB
Dimensions:  (year: 4645, month: 36, lat: 24, lon: 72)
Coordinates:
  * year     (year) int32 19kB 1 2 3 4 5 6 7 ... 4640 4641 4642 4643 4644 4645
  * month    (month) int32 144B 1 2 3 4 5 6 7 8 9 ... 28 29 30 31 32 33 34 35 36
  * lat      (lat) float32 96B -55.0 -50.0 -45.0 -40.0 ... 45.0 50.0 55.0 60.0
  * lon      (lon) float32 288B 0.0 5.0 10.0 15.0 ... 340.0 345.0 350.0 355.0
Data variables:
    sst      (year, month, lat, lon) float64 2GB 0.3464 0.3049 ... 0.5045 0.4406
    t300     (year, month, lat, lon) float64 2GB -0.2449 -0.3 ... 0.5158 0.5272
    ua       (year, month, lat, lon) float64 2GB -1.68 -1.947 ... 1.729 0.7234
    va       (year, month, lat, lon) float64 2GB -0.4895 -0.8997 ... -0.8812

In [49]:
temp = [cmip_data[var].isel(year=0, month=0).to_numpy() for var in ['sst', 't300']] # list of 24 (lat) x 72 (lon) arrays
lats = cmip_data['lat'].to_numpy() # 24
lats_features = np.repeat(np.sin(np.radians(lats))[:, np.newaxis], 72, axis=1)
temp.append(lats_features)
lons = cmip_data['lon'].to_numpy() # 72
lons_features = np.repeat(np.sin(np.radians(lons))[:, np.newaxis], 24, axis=1).T
temp.append(lons_features)

temp = np.stack(temp, axis=0) # 4 x 24 (lat) x 72 (lon)
print(temp[2])

[[-0.81915206 -0.81915206 -0.81915206 ... -0.81915206 -0.81915206
  -0.81915206]
 [-0.76604444 -0.76604444 -0.76604444 ... -0.76604444 -0.76604444
  -0.76604444]
 [-0.70710677 -0.70710677 -0.70710677 ... -0.70710677 -0.70710677
  -0.70710677]
 ...
 [ 0.76604444  0.76604444  0.76604444 ...  0.76604444  0.76604444
   0.76604444]
 [ 0.81915206  0.81915206  0.81915206 ...  0.81915206  0.81915206
   0.81915206]
 [ 0.86602545  0.86602545  0.86602545 ...  0.86602545  0.86602545
   0.86602545]]


In [13]:
print(cmip_data.isel(year=0, month=0)['sst'].to_numpy()[0, 0])
print(cmip_data.isel(year=0, month=0, lat=0, lon=0)['sst'])

0.346435546875
<xarray.DataArray 'sst' ()> Size: 8B
array(0.34643555)
Coordinates:
    year     int32 4B 1
    month    int32 4B 1
    lat      float32 4B -55.0
    lon      float32 4B 0.0


In [11]:
print(cmip_labels['nino'].to_numpy()[0])
print(cmip.get_labels()[0]) # checks out

print(cmip_data.isel(year=1, month=24)['sst'].to_numpy())
print(torch.load(f'{DATA_ROOT}/CMIP/processed/grid_37.pt')['x']) # checks out

[-0.26102549 -0.13325377 -0.01483156  0.10506672  0.24070978  0.3849988
  0.46769741  0.49836656  0.45298234  0.35320151  0.13045476 -0.22466083
 -0.51252842 -0.67330021 -0.69312692 -0.62691498 -0.54981941 -0.47077212
 -0.43879238 -0.45885882 -0.5298723  -0.66582316 -0.67307574 -0.53411871
 -0.16938901  0.16518302  0.42523685  0.51058745  0.61095256  0.73109442
  0.833076    0.78988576  0.74149543  0.70016259  0.69692588  0.62087137]
[ 0.62087137  0.36371359 -0.01698022 -0.53221828 -1.08626425 -1.66381609
 -2.2916038  -2.75982594 -3.09878922 -3.26644039 -3.32816887 -3.33858109
 -3.00591755 -2.55761647 -1.99520016 -1.65846097 -1.35466826 -1.01727855
 -0.65480739 -0.37268963 -0.27131057 -0.22853804 -0.21898462 -0.15724176]
[[ 1.05085111  1.33027625  1.39816737 ...  0.01287985  0.20934248
   0.87206316]
 [-0.25230312  0.06607008 -0.15661144 ... -0.70233774 -0.64120579
  -0.53867388]
 [-1.03491354 -0.89396858 -1.11103821 ... -1.15095615 -1.408494
  -1.34036255]
 ...
 [ 0.          0.      

/tmp/ipykernel_5533/3432033618.py:5: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  print(torch.load(f'{DATA_ROOT}/CMIP/processed/grid_37.pt')['x']) # checks out


In [21]:
test = SODA()
print(len(test.get_labels()))
print(test.len())
print(test.model_indices[0])

soda = xr.load_dataset(f'{DATA_ROOT}/SODA/raw/SODA_train.nc')
labels = xr.load_dataset(f'{DATA_ROOT}/SODA/raw/SODA_label.nc')

1189
1201
[   0    1    2 ... 1198 1199 1200]


In [23]:
print(labels['nino'].to_numpy()[0])
print(test.get_labels()[0]) # checks out

print(soda.isel(year=1, month=24)['sst'].to_numpy())
print(torch.load(f'{DATA_ROOT}/SODA/processed/grid_37.pt')['x']) # checks out

[-0.40720701 -0.20244436 -0.10386104 -0.02910841 -0.13252996 -0.25527564
 -0.3326247  -0.26293179 -0.08058987  0.10612228  0.21165498  0.16504486
  0.06697161  0.00999126 -0.00164753 -0.06598581 -0.14728385 -0.1915542
 -0.17029583 -0.19376083 -0.27808595 -0.39393583 -0.49975768 -0.58400702
 -0.73201811 -0.72508991 -0.58416802 -0.31754819 -0.12046373 -0.03802495
  0.013173    0.06823147  0.0597352   0.02755602  0.011619   -0.04931002]
-0.04931001737713814
[[ 0.11608636  0.18075694  0.21152487 ...  0.37119755  0.3891565
   0.34661946]
 [-0.0493145   0.14049093  0.08494244 ...  0.04397212  0.13710718
   0.02225389]
 [-0.40119675 -0.25743976 -0.58736014 ... -0.2782481  -0.72890866
  -1.1987113 ]
 ...
 [ 0.6951801   0.32021564  0.         ...  1.1926429   1.048556
   0.8786045 ]
 [ 1.3251534   1.7169532   1.73312    ...  0.9868533   0.55792874
   0.49789077]
 [ 1.2207191   1.4551113   1.094254   ...  0.9190947   0.6342436
   0.6626737 ]]
tensor([[ 0.1161,  0.0022],
        [ 0.1808, -0.0042

/tmp/ipykernel_14577/3290437918.py:5: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  print(torch.load(f'{DATA_ROOT}/SODA/processed/grid_37.pt')['x']) # checks out


In [2]:
from utils.data_utils import SGS
from torch_geometric.data import DataLoader
sampler = SGS(data_source=test, group_size=36, shuffle=False)
dataloader = DataLoader(test, sampler=sampler, batch_size=36)

counter = 0
b = None
for batch in dataloader:
    b = batch
    counter += 1
    if counter > 0:
        break

print(b.x) # checks out

AttributeError: 'NoneType' object has no attribute 'flatten'

In [32]:
print(cmip.isel(year=0)['sst'].to_numpy())

[[[ 3.46435547e-01  3.04903030e-01  2.32462883e-01 ... -1.25169754e-03
    6.58988953e-04  2.29776144e-01]
  [ 7.92360306e-03  2.02001572e-01 -3.77192497e-02 ... -3.67553234e-01
   -1.38951778e-01 -1.83049202e-01]
  [-6.67334557e-01 -5.47147751e-01 -4.79902267e-01 ... -1.30562210e+00
   -1.09991550e+00 -9.18848038e-01]
  ...
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ... -4.41954613e-01
   -2.57016182e-01  3.21140289e-01]
  [ 9.44924355e-02  3.67066383e-01  0.00000000e+00 ... -4.82238770e-01
   -2.99921989e-01  0.00000000e+00]
  [ 1.28334522e-01  0.00000000e+00  0.00000000e+00 ... -1.96497917e-01
   -1.70331955e-01 -1.12943649e-02]]

 [[ 2.22010851e-01  9.32629108e-02  5.45413494e-02 ...  2.87953854e-01
    5.49411774e-03  1.26200676e-01]
  [ 1.78332329e-02  2.81116962e-01  5.64475060e-02 ... -3.77742290e-01
   -1.42843246e-01 -3.74860764e-02]
  [-4.15350914e-01 -1.22386932e-01 -2.62648582e-01 ... -9.57970619e-01
   -8.51760864e-01 -7.72544861e-01]
  ...
  [ 0.00000000e+00  0.0

In [8]:
raw = xr.load_dataset('data/CMIP/raw/CMIP_train.nc')
print(np.sum(np.isnan(raw['va'].to_numpy())))
# print(np.shape(raw['t300'].to_numpy()))

13921123


In [5]:
raw

<xarray.Dataset> Size: 9GB
Dimensions:  (year: 4645, month: 36, lat: 24, lon: 72)
Coordinates:
  * year     (year) int32 19kB 1 2 3 4 5 6 7 ... 4640 4641 4642 4643 4644 4645
  * month    (month) int32 144B 1 2 3 4 5 6 7 8 9 ... 28 29 30 31 32 33 34 35 36
  * lat      (lat) float32 96B -55.0 -50.0 -45.0 -40.0 ... 45.0 50.0 55.0 60.0
  * lon      (lon) float32 288B 0.0 5.0 10.0 15.0 ... 340.0 345.0 350.0 355.0
Data variables:
    sst      (year, month, lat, lon) float64 2GB 0.3464 0.3049 ... 0.5045 0.4406
    t300     (year, month, lat, lon) float64 2GB -0.2449 -0.3 ... 0.5158 0.5272
    ua       (year, month, lat, lon) float64 2GB -1.68 -1.947 ... 1.729 0.7234
    va       (year, month, lat, lon) float64 2GB -0.4895 -0.8997 ... -0.8812

In [16]:
new = CMIP()
sampler = SGS(new, group_size=36, shuffle=False)
dataloader = DataLoader(new, sampler=sampler, batch_size=36)

counter = 0
b = None
for batch in dataloader:
    b = batch
    counter += 1
    if counter > 0:
        break

/tmp/ipykernel_99380/184516661.py:158: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  g = torch.load(osp.join(self.processed_dir, f'{year}_{month}.pt'))


In [27]:
raw = xr.open_dataset('data/CMIP/raw/CMIP_train.nc')
labels = xr.open_dataset('data/CMIP/raw/CMIP_label.nc')

raw['sst'].isel(year=0, month=0).to_numpy()

array([[ 3.46435547e-01,  3.04903030e-01,  2.32462883e-01, ...,
        -1.25169754e-03,  6.58988953e-04,  2.29776144e-01],
       [ 7.92360306e-03,  2.02001572e-01, -3.77192497e-02, ...,
        -3.67553234e-01, -1.38951778e-01, -1.83049202e-01],
       [-6.67334557e-01, -5.47147751e-01, -4.79902267e-01, ...,
        -1.30562210e+00, -1.09991550e+00, -9.18848038e-01],
       ...,
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
        -4.41954613e-01, -2.57016182e-01,  3.21140289e-01],
       [ 9.44924355e-02,  3.67066383e-01,  0.00000000e+00, ...,
        -4.82238770e-01, -2.99921989e-01,  0.00000000e+00],
       [ 1.28334522e-01,  0.00000000e+00,  0.00000000e+00, ...,
        -1.96497917e-01, -1.70331955e-01, -1.12943649e-02]])

In [29]:
labels['nino'].isel(year=2).to_numpy()

array([-0.16938901,  0.16518302,  0.42523685,  0.51058745,  0.61095256,
        0.73109442,  0.833076  ,  0.78988576,  0.74149543,  0.70016259,
        0.69692588,  0.62087137,  0.36371359, -0.01698022, -0.53221828,
       -1.08626425, -1.66381609, -2.2916038 , -2.75982594, -3.09878922,
       -3.26644039, -3.32816887, -3.33858109, -3.00591755, -2.55761647,
       -1.99520016, -1.65846097, -1.35466826, -1.01727855, -0.65480739,
       -0.37268963, -0.27131057, -0.22853804, -0.21898462, -0.15724176,
       -0.03204625])

In [30]:
print(b.x, new.get_labels()[0])

tensor([[  0.3464,  -0.2449,  -1.6803,  -0.4895],
        [  0.3049,  -0.3000,  -1.9474,  -0.8997],
        [  0.2325,  -0.3129,  -1.4455,  -1.2294],
        ...,
        [ -0.5733,  -0.5809, -10.5956,  -4.1250],
        [ -0.4048,  -0.4053,  -9.5165,  -2.5240],
        [ -0.6700,  -0.6705,  -7.1504,  -2.1535]]) [ 0.62087137  0.36371359 -0.01698022 -0.53221828 -1.08626425 -1.66381609
 -2.2916038  -2.75982594 -3.09878922 -3.26644039 -3.32816887 -3.33858109
 -3.00591755 -2.55761647 -1.99520016 -1.65846097 -1.35466826 -1.01727855
 -0.65480739 -0.37268963 -0.27131057 -0.22853804 -0.21898462 -0.15724176]
